---
jobs:
  - script: >
      job('seed-job') {
        logRotator {
            artifactDaysToKeep(-1)
            artifactNumToKeep(-1)
            daysToKeep(-1)
            numToKeep(10)
        }
        scm {
          git {
            remote {
              url("https://github.com/patryksandomierski/jenkins-casc.git")
            }
            branch('master')
          }
        }
        //triggers { cron('H/10 * * * *') }
        steps {
          dsl {
            external('jobs/dsl/*.groovy')
            ignoreExisting(false)
            removeAction('DELETE')
            removeViewAction('DELETE')
          }
        }
      }
...
